In [28]:
import pandas as pd

In [29]:
pwd

'/Users/yukiogawa/hacks/cmmc/Data/Homelessness_Rate'

In [50]:
comTrust = pd.read_csv("Community_Trust.csv", skiprows=6, names=["Neighborhood","Year", "Data Format", "Community Trust", "FIPS"])
empRate = pd.read_csv("Employment_Ratio.csv",skiprows=6, names=["Neighborhood","Year", "Data Format", "Employment Ratio", "FIPS"])
housingCondition = pd.read_csv("Fair_to_Poor_Housing.csv",skiprows=6, names=["Neighborhood","Year", "Data Format", "Fair or Poor rate", "FIPS"])
shelterPop = pd.read_csv("Families_in_Shelters.csv",skiprows=6, names=["Neighborhood","Year", "Data Format", "Homeless Families", "FIPS"])
occupiedPubHousing = pd.read_csv("Occupied_Public_Housing_Rent_Regulated_Units.csv",skiprows=6, names=["Neighborhood","Housing Type","Year", "Data Format", "Number of Housing", "FIPS"])
overcrowdedRentalHousing = pd.read_csv("Overcrowded_Rental_Housing.csv",skiprows=6, names=["Neighborhood","Year", "Data Format", "Overcrowsed Rental Housing", "FIPS"])
parentalEmploymentInstability = pd.read_csv("Parental_Employment_Instability.csv",skiprows=6, names=["Neighborhood","Year", "Data Format", "Unstable Emp Rate", "FIPS"])
residUnitbyBuildingType = pd.read_csv("Residential_Units_by_Building_Type.csv",skiprows=6, names=["Neighborhood","Building Type","Year", "Data Format", "Data", "FIPS"])
tierIIhomelessShelterCapacity = pd.read_csv("Tier_II_Homeless_Shelter_Capacity.csv",skiprows=6, names=["Neighborhood","Year", "Data Format", "Tier II Homeless Shelter Capacity", "FIPS"])

In [99]:
clean_comTrust = comTrust.drop(columns= ["Data Format", "FIPS"])
clean_comTrust.to_csv("community_trust_2015_2017.csv", index=False)

In [100]:
clean_empRate = empRate.drop(columns = ["Data Format", "FIPS"])
clean_empRate.to_csv("employment_ratio.csv_2005_2022", index=False)

In [101]:
clean_housingCondition = housingCondition.drop(columns = ["Data Format","FIPS"])
clean_housingCondition.to_csv("housing_condition_2011_2017.csv", index=False)

In [105]:
clean_parentalEmploymentInstability = parentalEmploymentInstability.drop(columns = ["Data Format","FIPS"])
clean_parentalEmploymentInstability = clean_parentalEmploymentInstability.sort_values('Year')

clean_parentalEmploymentInstability.to_csv("parental_employment_instability_2005_2022.csv", index=False)
clean_parentalEmploymentInstability

              Neighborhood  Year  Unstable Emp Rate
609        Elmhurst/Corona  2005            0.30808
230     University Heights  2005            0.56722
225   Concourse/Highbridge  2005            0.48807
206             Morrisania  2005            0.56482
465            Bensonhurst  2005            0.27642
...                    ...   ...                ...
1067              Bushwick  2022            0.26800
1068         East New York  2022            0.39400
1069            Park Slope  2022            0.18700
1054            Morrisania  2022            0.52000
1104         New York City  2022            0.33300

[1105 rows x 3 columns]

In [106]:
clean_tierIIhomelessShelterCapacity = tierIIhomelessShelterCapacity.drop(columns = ["Data Format","FIPS"])
clean_tierIIhomelessShelterCapacity.to_csv("tierII_homeless_shelter_capacity_2004_2011.csv", index = False)

In [108]:
clean_shelterPop_Rate = clean_shelterPop.loc[clean_shelterPop["Data Format"].str.contains("Rate", case = False, na= False)]
clean_shelterPop_Rate = clean_shelterPop_Rate.drop(columns = ["Data Format"])
clean_shelterPop_Rate.to_csv("shelter_population.csv_2005_2015", index = False)
clean_shelterPop_Rate

              Neighborhood  Year  Homeless Families
0            New York City  2005            2.75792
2                Manhattan  2005            1.73767
5     Battery Park/Tribeca  2005            0.35641
6        Greenwich Village  2005            0.27669
9          Lower East Side  2005            1.92616
...                    ...   ...                ...
1429           Tottenville  2015            0.21548
1433         New York City  2016            4.27345
1434         New York City  2017            3.98617
1435         New York City  2018            3.81567
1437         New York City  2019            3.72622

[719 rows x 3 columns]

In [110]:
clean_occupiedPubHousing_pubHousing = clean_occupiedPubHousing.loc[clean_occupiedPubHousing["Housing Type"].str.contains("Public Housing", case = False, na = False)]
clean_occupiedPubHousing_pubHousing = clean_occupiedPubHousing_pubHousing.drop(columns = ["Data Format", "Housing Type"])
clean_occupiedPubHousing_pubHousing["Number of Public Housing"] = clean_occupiedPubHousing_pubHousing["Number of Housing"]
clean_occupiedPubHousing_pubHousing = clean_occupiedPubHousing_pubHousing.drop(columns = ["Number of Housing"])

clean_occupiedPubHousing_pubHousing.to_csv("occupiedPubHousing_2002_2017.csv", index=False)
clean_occupiedPubHousing

,Neighborhood,Housing Type,Year,Data Format,Number of Housing
0,Battery Park/Tribeca,Public Housing,2002,Number,0.00000
1,Battery Park/Tribeca,Rent Regulated,2002,Number,13139.80449
2,Greenwich Village,Public Housing,2002,Number,0.00000
3,Greenwich Village,Rent Regulated,2002,Number,19397.03896
4,Lower East Side,Public Housing,2002,Number,16493.74850
...,...,...,...,...,...
1555,Queens,Rent Regulated,2017,Percent,0.43640
1556,Staten Island,Public Housing,2017,Percent,0.07909
1557,Staten Island,Rent Regulated,2017,Percent,0.22942
1558,New York City,Public Housing,2017,Percent,0.08787
1559,New York City,Rent Regulated,2017,Percent,0.49352

In [111]:
clean_occupiedPubHousing_rentRegulated = clean_occupiedPubHousing.loc[clean_occupiedPubHousing["Housing Type"].str.contains("Rent Regulated", case = False, na = False)]
clean_occupiedPubHousing_rentRegulated = clean_occupiedPubHousing_rentRegulated.drop(columns = ["Data Format", "Housing Type"])
clean_occupiedPubHousing_rentRegulated["Number of Rent Regulated Housing"] = clean_occupiedPubHousing_rentRegulated["Number of Housing"]
clean_occupiedPubHousing_rentRegulated = clean_occupiedPubHousing_rentRegulated.drop(columns = ["Number of Housing"])

clean_occupiedPubHousing_rentRegulated.to_csv("occupiedRentRegulated_2002_2017.csv", index=False)

In [89]:
clean_residUnitBuildingType_oneAndTwoFamily = clean_residUnitBuildingType.loc[clean_residUnitBuildingType["Building Type"].str.contains("One and Two Family", case = False, na = False)]
clean_residUnitBuildingType_oneAndTwoFamily_Percent = clean_residUnitBuildingType_oneAndTwoFamily.loc[clean_residUnitBuildingType_oneAndTwoFamily["Data Format"].str.contains("Percent", case = False, na = False)]

clean_residUnitBuildingType_oneAndTwoFamily_Percent = clean_residUnitBuildingType_oneAndTwoFamily_Percent.drop(columns = ["Data Format"])
clean_residUnitBuildingType_oneAndTwoFamily_Percent["Percentage of one and two family resident unit"] = clean_residUnitBuildingType_oneAndTwoFamily_Percent["Data"]
clean_residUnitBuildingType_oneAndTwoFamily_Percent = clean_residUnitBuildingType_oneAndTwoFamily_Percent.drop(columns = ["Data", "Building Type"])
clean_residUnitBuildingType_oneAndTwoFamily_Percent.to_csv("one_and_two_family_resident_unit_2018.csv")

In [88]:
clean_residUnitBuildingType_MultiFamily_WalkUp = clean_residUnitBuildingType.loc[clean_residUnitBuildingType["Building Type"].str.contains("Multi-Family Walk-Up", case = False, na = False)]
clean_residUnitBuildingType_MultiFamily_WalkUp_Percent = clean_residUnitBuildingType_MultiFamily.loc[clean_residUnitBuildingType_MultiFamily["Data Format"].str.contains("Percent", case = False, na = False)]

clean_residUnitBuildingType_MultiFamily_WalkUp_Percent = clean_residUnitBuildingType_MultiFamily_WalkUp_Percent.drop(columns = ["Data Format"])
clean_residUnitBuildingType_MultiFamily_WalkUp_Percent["Percentage of multiple family with walk up resident unit"] = clean_residUnitBuildingType_MultiFamily_WalkUp_Percent["Data"]
clean_residUnitBuildingType_MultiFamily_WalkUp_Percent = clean_residUnitBuildingType_MultiFamily_WalkUp_Percent.drop(columns = ["Data", "Building Type"])
clean_residUnitBuildingType_MultiFamily_WalkUp_Percent.to_csv("multi_family_walkup_resident_unit_2018.csv")

In [87]:
clean_residUnitBuildingType_MultiFamily_Elevator = clean_residUnitBuildingType.loc[clean_residUnitBuildingType["Building Type"].str.contains("Multi-Family Elevator", case = False, na = False)]

clean_residUnitBuildingType_MultiFamily_Elevator_Percent = clean_residUnitBuildingType_MultiFamily.loc[clean_residUnitBuildingType_MultiFamily["Data Format"].str.contains("Percent", case = False, na = False)]

clean_residUnitBuildingType_MultiFamily_Elevator_Percent = clean_residUnitBuildingType_MultiFamily_Elevator_Percent.drop(columns = ["Data Format"])
clean_residUnitBuildingType_MultiFamily_Elevator_Percent["Percentage of multiple family with elevator resident unit"] = clean_residUnitBuildingType_MultiFamily_Elevator_Percent["Data"]
clean_residUnitBuildingType_MultiFamily_Elevator_Percent = clean_residUnitBuildingType_MultiFamily_Elevator_Percent.drop(columns = ["Data", "Building Type"])
clean_residUnitBuildingType_MultiFamily_Elevator_Percent.to_csv("multi_family_elevator_unit_2018.csv")

In [97]:
clean_residUnitBuildingType_Mixed_Commercial = clean_residUnitBuildingType.loc[clean_residUnitBuildingType["Building Type"].str.contains("Mixed Residential and Commercial", case = False, na = False)]

clean_residUnitBuildingType_Mixed_Commercial_Percent = clean_residUnitBuildingType_Mixed_Commercial.loc[clean_residUnitBuildingType_Mixed_Commercial["Data Format"].str.contains("Percent", case = False, na = False)]

clean_residUnitBuildingType_Mixed_Commercial_Percent = clean_residUnitBuildingType_Mixed_Commercial_Percent.drop(columns = ["Data Format"])
clean_residUnitBuildingType_Mixed_Commercial_Percent["Percentage of mixed and commercial resident unit"] = clean_residUnitBuildingType_Mixed_Commercial_Percent["Data"]
clean_residUnitBuildingType_Mixed_Commercial_Percent = clean_residUnitBuildingType_Mixed_Commercial_Percent.drop(columns = ["Data", "Building Type"])
clean_residUnitBuildingType_Mixed_Commercial_Percent.to_csv("mixed_commercial_resident_unit_2018.csv")

'/Users/yukiogawa/hacks/cmmc/Data/Homelessness_Rate'